server:
  port: 9002

spring:
  application:
    name: blog-post
  data:
    mongodb:
      database: blog-microservice

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka


spring.sleuth.sampler.percentage: 1.0